products:
  - name: "commerce"
    display_name: "Adobe Commerce/Magento"  
    url: "https://helpx.adobe.com/security/products/magento.html"
    enabled: true
  - name: "experience-manager"
    display_name: "Adobe Experience Manager"
    url: "https://helpx.adobe.com/security/products/experience-manager.html" 
    enabled: false  # Disabled - focus on Commerce only
  - name: "experience-platform"
    display_name: "Adobe Experience Platform"
    url: "https://helpx.adobe.com/security/products/experience-platform.html"
    enabled: false  # 404 currently

scraper:
  user_agent: "Mozilla/5.0 (compatible; AdobeDigest-SecurityScraper/1.0; +https://adobedigest.com)"
  rate_limit: "15s"       # Much longer delay for CDN respect
  timeout: "60s"          # Longer timeout for CDN delays
  retry_attempts: 1       # Fewer retries to avoid triggering blocks
  concurrent_limit: 1     # Single threaded to appear human-like

output:
  content_dir: "content"
  rss_file: "static/feeds/bulletins.xml"
  cache_file: ".scraper-cache.json"
  
rss:
  title: "Adobe Security Bulletins"
  description: "Latest security updates for Adobe Commerce, AEM, and Experience Platform"
  link: "https://adobedigest.com/bulletins/"
  max_items: 50
