baseURL = "https://adobedigest.com"
languageCode = "en-us"
title = "Adobe Digest"

# Enable Hugo modules
[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

# Hextra theme configuration
[params]
  # Navbar configuration
  [params.navbar]
    displayTitle = true
    displayLogo = false
    width = "wide" # Can be "normal", "wide", or "full"
  
  # Footer configuration
  [params.footer]
    enable = true
  
  # Enable search
  [params.search]
    enable = true
  
  # Enable edit page links
  [params.editPage]
    enable = true
    repository = "https://github.com/superterran/adobe-digest"
    branch = "main"
    path = "content"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "All Bulletins"
    url = "/bulletins/"
    weight = 2
  
  [[menu.main]]
    name = "Products"
    weight = 3
    hasChildren = true
  
  [[menu.main]]
    name = "Creative Cloud"
    parent = "Products"
    url = "/products/?filter=creative"
    weight = 31
  
  [[menu.main]]
    name = "Document Cloud"
    parent = "Products"
    url = "/products/?filter=document"
    weight = 32
  
  [[menu.main]]
    name = "Commerce"
    parent = "Products"
    url = "/products/?filter=commerce"
    weight = 33
  
  [[menu.main]]
    name = "Experience Manager"
    parent = "Products"
    url = "/products/?filter=experience"
    weight = 34

# Markup configuration for code highlighting
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true

# Build configuration
[build]
  writeStats = true
