baseURL = "https://superterran.github.io/adobe-digest"
languageCode = "en-us"
title = "Adobe Digest"

# Enable Hugo modules
[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

# Hextra theme configuration
[params]
  # Navbar configuration
  [params.navbar]
    displayTitle = true
    displayLogo = false
    width = "wide" # Can be "normal", "wide", or "full"
  
  # Footer configuration
  [params.footer]
    enable = true
  
  # Enable search
  [params.search]
    enable = true
  
  # Enable edit page links
  [params.editPage]
    enable = true
    repository = "https://github.com/superterran/adobe-digest"
    branch = "main"
    path = "content"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

# Markup configuration for code highlighting
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true

# Build configuration
[build]
  writeStats = true
