name: Scrape bulletins

on:
  schedule:
    - cron: '0 3,15 * * *' # twice daily UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Tidy and build scraper
        run: |
          go mod tidy
          go build -o bin/scraper ./cmd/scraper

      - name: Run scraper
        run: ./bin/scraper

      - name: Commit and push if changes
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add content/bulletins
            git commit -m "chore(scrape): update bulletins [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
