name: Update Adobe Security Content
on:
  workflow_dispatch:
    inputs:
      add_bulletin:
        description: 'Add new bulletin (JSON format)'
        required: false
        type: string
      regenerate_only:
        description: 'Only regenerate content (no new bulletin)'
        required: false
        type: boolean
        default: false
  schedule:
    # Run weekly to regenerate content
    - cron: '0 0 * * 0'

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: go mod download
      
    - name: Add new bulletin (if provided)
      if: github.event.inputs.add_bulletin != '' && github.event.inputs.regenerate_only != true
      run: |
        echo "Adding new bulletin and regenerating content..."
        go run cmd/content-generator/main.go add '${{ github.event.inputs.add_bulletin }}'
        
    - name: Generate all content
      if: github.event.inputs.add_bulletin == '' || github.event.inputs.regenerate_only == true
      run: |
        echo "Regenerating all content from database..."
        go run cmd/content-generator/main.go generate
        
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        
    - name: Build Hugo site
      run: hugo --minify
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        
    - name: Commit updated data
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add data/security-bulletins.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update security bulletins database"
          git push
        fi
